
// 테이블 초기화
DROP TABLE "NOTICE_FILE"; // 공지 파일
DROP TABLE "SELLER_FILE"; // 판매자 파일
DROP TABLE "GOODS_FILE"; // 상품 파일
DROP TABLE "REVIEW_FILE"; // 후기 파일
DROP TABLE "PROMOTION_FILE"; // 홍보 파일
DROP TABLE "INQUIRY_FILE"; // 문의 파일
DROP TABLE "INIQUIRY_FILE"; // 예전 문의 파일

DROP TABLE "SELL_REPLY"; // 상품 판매 댓글
DROP TABLE "PROMOTION_REPLY"; // 홍보 댓글
DROP TABLE "REVIEW_REPLY"; // 후기 댓글
DROP TABLE "INQUIRY_REPLY"; // 문의 댓글
DROP TABLE "INIQUIRY_REPLY"; // 예전 문의 댓글

DROP TABLE "CART"; // 장바구니
DROP TABLE "LIKE"; // 좋아요
DROP TABLE "SUBSCRIBE"; // 찜

DROP TABLE "NOTICE"; // 공지
DROP TABLE "INQUIRY"; // 문의
DROP TABLE "INIQUIRY"; // 예전 문의
DROP TABLE "PROMOTION"; // 홍보
DROP TABLE "REVIEW"; // 후기

DROP TABLE "GOODS_SELL"; // 상품 판매
DROP TABLE "GOODS_ORDER"; // 예전 주문 상품
DROP TABLE "ORDER_GOODS"; // 주문 상품
DROP TABLE "ORDER"; // 주문

DROP TABLE "GOODS"; // 상품
DROP TABLE "SELLER"; // 판매자
DROP TABLE "MEMBER"; // 회원

//==============================================================================
// 테이블 시퀀스 초기화
DROP SEQUENCE SEQ_MNO; // 회원
DROP SEQUENCE SEQ_SNO; // 판매자
DROP SEQUENCE SEQ_GNO; // 상품

DROP SEQUENCE SEQ_ONO; // 주문
DROP SEQUENCE SEQ_GSNO; // 상품 판매
DROP SEQUENCE SEQ_ODNO; // 예전 주문 상품
DROP SEQUENCE SEQ_OGNO; // 주문 상품

DROP SEQUENCE SEQ_NNO; // 공지
DROP SEQUENCE SEQ_INO; // 문의
DROP SEQUENCE SEQ_PNO; // 홍보
DROP SEQUENCE SEQ_RNO; // 후기

DROP SEQUENCE SEQ_CNO; // 장바구니


DROP SEQUENCE SEQ_SRNO; // 상품 판매 댓글
DROP SEQUENCE SEQ_PRNO; // 홍보 댓글
DROP SEQUENCE SEQ_RRNO; // 후기 댓글
DROP SEQUENCE SEQ_IRNO; // 문의 댓글

DROP SEQUENCE SEQ_NFNO; // 공지 파일
DROP SEQUENCE SEQ_SFNO; // 판매자 파일
DROP SEQUENCE SEQ_GFNO; // 상품 파일
DROP SEQUENCE SEQ_RFNO; // 후기 파일
DROP SEQUENCE SEQ_PFNO; // 홍보 파일
DROP SEQUENCE SEQ_IFNO; // 문의 파일


//==============================================================================
// 시퀀스 생성
CREATE SEQUENCE SEQ_MNO; // 회원
CREATE SEQUENCE SEQ_SNO; // 판매자
CREATE SEQUENCE SEQ_GNO; // 상품

CREATE SEQUENCE SEQ_ONO; // 주문
CREATE SEQUENCE SEQ_GSNO; // 상품 판매
// CREATE SEQUENCE SEQ_ODNO; // 주문 상품
CREATE SEQUENCE SEQ_OGNO; // 주문 상품

CREATE SEQUENCE SEQ_NNO; // 공지
CREATE SEQUENCE SEQ_INO; // 문의
CREATE SEQUENCE SEQ_PNO; // 홍보
CREATE SEQUENCE SEQ_RNO; // 후기

CREATE SEQUENCE SEQ_CNO; // 장바구니

CREATE SEQUENCE SEQ_SRNO; // 상품 판매 댓글
CREATE SEQUENCE SEQ_PRNO; // 홍보 댓글
CREATE SEQUENCE SEQ_RRNO; // 후기 댓글
CREATE SEQUENCE SEQ_IRNO; // 문의 댓글

CREATE SEQUENCE SEQ_NFNO; // 공지 파일
CREATE SEQUENCE SEQ_SFNO; // 판매자 파일
CREATE SEQUENCE SEQ_GFNO; // 상품 파일
CREATE SEQUENCE SEQ_RFNO; // 후기 파일
CREATE SEQUENCE SEQ_PFNO; // 홍보 파일
CREATE SEQUENCE SEQ_IFNO; // 문의 파일

//==============================================================================
// 회원 테이블 생성
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	    NUMBER		        NOT NULL,
	"MEMBER_ID"	    VARCHAR(25)		    NOT NULL UNIQUE,
	"MEMBER_PWD"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(15)		NOT NULL,
	"EMAIL"	        VARCHAR2(40)		NOT NULL,
	"PHONE"	        VARCHAR2(13)		NOT NULL,
    "ZIP_CODE"      VARCHAR2(5)         NOT NULL,              
	"ADDRESS"	    VARCHAR2(100)		NOT NULL,
    "DETAIL_ADDRESS"VARCHAR2(100 BYTE)  NOT NULL,
	"GENDER"	    CHAR(1)		        NOT NULL,
	"STATUS"	    DATE		        NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '아이디(영어, 숫자, 특수문자  6~12자 사이)';
COMMENT ON COLUMN "MEMBER"."MEMBER_PWD" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';
COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';
COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호(-포함 13자리)';
COMMENT ON COLUMN "MEMBER"."ZIP_CODE" IS '우편 번호';
COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';
COMMENT ON COLUMN "MEMBER"."DETAIL_ADDRESS" IS '상세 주소';
COMMENT ON COLUMN "MEMBER"."GENDER" IS '성별(M,F)';
COMMENT ON COLUMN "MEMBER"."STATUS" IS '탈퇴일';

//==============================================================================
// 판매자 테이블 생성
CREATE TABLE "SELLER" (
	"SELLER_NO"	        NUMBER		        NOT NULL,
	"COMPANY_NAME"	    VARCHAR2(100)		NOT NULL,
	"SELLER_ID"	        VARCHAR2(25)		NOT NULL,
	"SELLER_PWD"	    VARCHAR2(100)		NOT NULL,
	"SELLER_NAME"	    VARCHAR2(20)		NOT NULL,
	"COMPANY_NO"	    VARCHAR2(20)		NOT NULL,
	"BUSINESS_NO"	    VARCHAR2(35)		NOT NULL,
	"ADDRESS"	        VARCHAR2(100)		NOT NULL,
	"EMAIL"	            VARCHAR2(40)		NOT NULL,
	"PHONE"	            VARCHAR2(13)		NOT NULL,
	"ACCOUNT_NO"	    VARCHAR2(30)		NOT NULL,
	"DELETE_DATE"	    DATE		        NULL,
	"ENROLL_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"ACCEPT_DATE"	    DATE		        NULL,
	"REFUSE_REASON"	    VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "SELLER"."SELLER_NO" IS '판매자 번호';
COMMENT ON COLUMN "SELLER"."COMPANY_NAME" IS '상호명';
COMMENT ON COLUMN "SELLER"."SELLER_ID" IS '아이디';
COMMENT ON COLUMN "SELLER"."SELLER_PWD" IS '비밀번호';
COMMENT ON COLUMN "SELLER"."SELLER_NAME" IS '대표자 이름';
COMMENT ON COLUMN "SELLER"."COMPANY_NO" IS '사업자 등록 번호(000-000-0000 의 형식)';
COMMENT ON COLUMN "SELLER"."BUSINESS_NO" IS '통신 판매 번호(XXX-00000호 형식)';
COMMENT ON COLUMN "SELLER"."ADDRESS" IS '소재지';
COMMENT ON COLUMN "SELLER"."EMAIL" IS '메일 주소';
COMMENT ON COLUMN "SELLER"."PHONE" IS '전화 번호(-를 포함)';
COMMENT ON COLUMN "SELLER"."ACCOUNT_NO" IS '계좌 번호(-를 포함)';
COMMENT ON COLUMN "SELLER"."DELETE_DATE" IS '탈퇴일';
COMMENT ON COLUMN "SELLER"."ENROLL_DATE" IS '가입일';
COMMENT ON COLUMN "SELLER"."ACCEPT_DATE" IS '승인일';
COMMENT ON COLUMN "SELLER"."REFUSE_REASON" IS '회원가입 거절 사유';

//==============================================================================
// 상품 테이블 생성
CREATE TABLE "GOODS" (
	"GOOD_NO"	        NUMBER		        NOT NULL,
	"SELLER_NO"	        NUMBER		        NOT NULL,
	"GOOD_TITLE"	    VARCHAR2(100)		NOT NULL,
	"GOOD_DETAIL"	    VARCHAR2(3000)		NULL,
	"ORIGIN"	        VARCHAR2(100)		NOT NULL,
	"PRICE"	            NUMBER		        NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"		DATE		        NULL,
	"EXPIRATION_DATE"	DATE		        NOT NULL,
	"STOCK"	            NUMBER	            DEFAULT 0	NULL
);

COMMENT ON COLUMN "GOODS"."GOOD_NO" IS '상품 번호';
COMMENT ON COLUMN "GOODS"."SELLER_NO" IS '판매자 번호';
COMMENT ON COLUMN "GOODS"."GOOD_TITLE" IS '품목';
COMMENT ON COLUMN "GOODS"."GOOD_DETAIL" IS '상품 상세 정보';
COMMENT ON COLUMN "GOODS"."ORIGIN" IS '원산지';
COMMENT ON COLUMN "GOODS"."PRICE" IS '판매가';
COMMENT ON COLUMN "GOODS"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "GOODS"."DELETE_DATE" IS '삭제일';
COMMENT ON COLUMN "GOODS"."EXPIRATION_DATE" IS '유통기한';
COMMENT ON COLUMN "GOODS"."STOCK" IS '재고(0 일시 구매X)';

//==============================================================================
// 주문 테이블 생성
CREATE TABLE "ORDER" (
	"ORDER_NO"	        NUMBER		        NOT NULL,
	"MEMBER_NO"	        NUMBER		        NOT NULL,
	"ORDER_NAME"	    VARCHAR2(15)		NOT NULL,
	"PHONE"	            VARCHAR2(13)		NOT NULL,
	"PRICE"	            NUMBER		        NOT NULL,
	"ZIP_CODE"	        VARCHAR2(5 BYTE)    NOT NULL,
	"ADDRESS"	        VARCHAR2(100)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(100)		NOT NULL,
	"REQUEST"	        VARCHAR2(200)		NULL,
	"PAY_TID"	        VARCHAR2(100)		NULL,
	"PAY_METHOD"	    VARCHAR2(100)		NULL,
	"PAY_DATE"	        DATE	            DEFAULT SYSDATE	NOT NULL,
	"PAY_CANCEL"	    DATE		        NULL,
	"STATUS"	        DATE		        NULL
);

COMMENT ON COLUMN "ORDER"."ORDER_NO" IS '주문 번호';
COMMENT ON COLUMN "ORDER"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "ORDER"."ORDER_NAME" IS '이름';
COMMENT ON COLUMN "ORDER"."PHONE" IS '전화 번호';
COMMENT ON COLUMN "ORDER"."PRICE" IS '총 가격';
COMMENT ON COLUMN "ORDER"."ZIP_CODE" IS '우편 번호';
COMMENT ON COLUMN "ORDER"."ADDRESS" IS '주소';
COMMENT ON COLUMN "ORDER"."DETAIL_ADDRESS" IS '상세 주소';
COMMENT ON COLUMN "ORDER"."REQUEST" IS '배송시 요청 사항';
COMMENT ON COLUMN "ORDER"."PAY_TID" IS '결제 고유 번호';
COMMENT ON COLUMN "ORDER"."PAY_METHOD" IS '결제 방법';
COMMENT ON COLUMN "ORDER"."PAY_DATE" IS '결제일';
COMMENT ON COLUMN "ORDER"."PAY_CANCEL" IS '환불일';
COMMENT ON COLUMN "ORDER"."STATUS" IS '결제 완료 상태';

//==============================================================================
// 상품 판매 테이블 생성
CREATE TABLE "GOODS_SELL" (
	"SELL_NO"	        NUMBER		        NOT NULL,
	"SELLER_NO"	        NUMBER		        NOT NULL,
	"GOOD_NO"	        NUMBER		        NOT NULL,
	"SELL_TITLE"	    VARCHAR2(100)		NOT NULL,
	"SELL_CONTENT"	    VARCHAR2(3000)		NOT NULL,
	"COUNT"	            NUMBER	            DEFAULT 0	NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "GOODS_SELL"."SELL_NO" IS '상품 판매 번호';
COMMENT ON COLUMN "GOODS_SELL"."SELLER_NO" IS '판매자 번호';
COMMENT ON COLUMN "GOODS_SELL"."GOOD_NO" IS '상품 번호';
COMMENT ON COLUMN "GOODS_SELL"."SELL_TITLE" IS '제목';
COMMENT ON COLUMN "GOODS_SELL"."SELL_CONTENT" IS '내용';
COMMENT ON COLUMN "GOODS_SELL"."COUNT" IS '조회수';
COMMENT ON COLUMN "GOODS_SELL"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "GOODS_SELL"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 주문 상품 테이블 생성
CREATE TABLE "ORDER_GOODS" (
	"ORDER_DETAIL_NO"	    NUMBER		NOT NULL,
	"ORDER_NO"	            NUMBER		NOT NULL,
	"GOOD_NO"	            NUMBER		NOT NULL,
	"COUNT"	                NUMBER		NOT NULL,
	"PRICE"	                NUMBER		NOT NULL,
	"STATUS"	            CHAR(1)	    DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "ORDER_GOODS"."ORDER_DETAIL_NO" IS '주문 상세 번호';
COMMENT ON COLUMN "ORDER_GOODS"."ORDER_NO" IS '주문 번호';
COMMENT ON COLUMN "ORDER_GOODS"."GOOD_NO" IS '상품 번호';
COMMENT ON COLUMN "ORDER_GOODS"."COUNT" IS '수량';
COMMENT ON COLUMN "ORDER_GOODS"."PRICE" IS '상품별 가격';
COMMENT ON COLUMN "ORDER_GOODS"."STATUS" IS '주문 처리 상태';

//==============================================================================
// 공지 테이블 생성
CREATE TABLE "NOTICE" (
	"NOTICE_NO"	        NUMBER		        NOT NULL,
	"NOTICE_TITLE"	    VARCHAR2(400)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"COUNT"	            NUMBER	            DEFAULT 0	NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지사항 번호';
COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '제목';
COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '내용';
COMMENT ON COLUMN "NOTICE"."COUNT" IS '조회수';
COMMENT ON COLUMN "NOTICE"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "NOTICE"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 문의 테이블 생성
CREATE TABLE "INQUIRY" (
	"INQ_NO"	        NUMBER		        NOT NULL,
	"SELLER_NO"	        NUMBER		        NOT NULL,
	"MEMBER_NO"	        NUMBER		        NOT NULL,
	"INQ_TITLE"	        VARCHAR2(400)		NOT NULL,
	"INQ_CONTENT"	    VARCHAR2(3000)		NOT NULL,
	"COUNT"	            NUMBER	            DEFAULT 0	NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL,
	"RESPONSE_CONTENT"	VARCHAR2(4000)		NULL,
	"RESPONSE_DATE"	    DATE		        NULL  
);

COMMENT ON COLUMN "INQUIRY"."INQ_NO" IS '문의 번호';
COMMENT ON COLUMN "INQUIRY"."SELLER_NO" IS '판매자 번호';
COMMENT ON COLUMN "INQUIRY"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "INQUIRY"."INQ_TITLE" IS '제목';
COMMENT ON COLUMN "INQUIRY"."INQ_CONTENT" IS '내용';
COMMENT ON COLUMN "INQUIRY"."COUNT" IS '조회수';
COMMENT ON COLUMN "INQUIRY"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "INQUIRY"."DELETE_DATE" IS '삭제일';
COMMENT ON COLUMN "INQUIRY"."RESPONSE_CONTENT" IS '답변';
COMMENT ON COLUMN "INQUIRY"."RESPONSE_DATE" IS '답변일';

//==============================================================================
// 홍보 테이블 생성
CREATE TABLE "PROMOTION" (
	"PROMOTION_NO"	        NUMBER		        NOT NULL,
	"SELLER_NO"	            NUMBER		        NOT NULL,
	"PROMOTION_TITLE"	    VARCHAR2(100)		,
	"PROMOTION_CONTENT"	    VARCHAR2(3000)		NOT NULL,
	"COUNT"	                NUMBER	            DEFAULT 0	NOT NULL,
	"CREATE_DATE"	        DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	        DATE		        NULL
);

COMMENT ON COLUMN "PROMOTION"."PROMOTION_NO" IS '홍보 번호';
COMMENT ON COLUMN "PROMOTION"."SELLER_NO" IS '판매자 번호';
COMMENT ON COLUMN "PROMOTION"."PROMOTION_TITLE" IS '제목';
COMMENT ON COLUMN "PROMOTION"."PROMOTION_CONTENT" IS '내용';
COMMENT ON COLUMN "PROMOTION"."COUNT" IS '조회수';
COMMENT ON COLUMN "PROMOTION"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "PROMOTION"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 후기 테이블 생성
CREATE TABLE "REVIEW" (
	"REV_NO"	        NUMBER		        NOT NULL,
	"MEMBER_NO"	        NUMBER		        NOT NULL,
	"GOOD_NO"	        NUMBER		        NOT NULL,
	"REV_TITLE"	        VARCHAR2(100),		
	"REV_CONTENT"	    VARCHAR2(3000)		NOT NULL,
	"COUNT"	            NUMBER	            DEFAULT 0	NOT NULL,
    "STAR_RATING"	    NUMBER	            DEFAULT 0	NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "REVIEW"."REV_NO" IS '후기 번호';
COMMENT ON COLUMN "REVIEW"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "REVIEW"."GOOD_NO" IS '상품 번호';
COMMENT ON COLUMN "REVIEW"."REV_TITLE" IS '제목';
COMMENT ON COLUMN "REVIEW"."REV_CONTENT" IS '내용';
COMMENT ON COLUMN "REVIEW"."COUNT" IS '조회수';
COMMENT ON COLUMN "REVIEW"."STAR_RATING" IS '별점';
COMMENT ON COLUMN "REVIEW"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "REVIEW"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 장바구니 테이블 생성
CREATE TABLE "CART" (
	"CART_NO"	        NUMBER		NOT NULL,
	"MEMBER_NO"     	NUMBER		NOT NULL,
	"GOOD_NO"	        NUMBER		NOT NULL,
	"COUNT"	            NUMBER		NOT NULL,
	"STATUS"	        CHAR(1)	    DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "CART"."CART_NO" IS '장바구니 번호';
COMMENT ON COLUMN "CART"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "CART"."GOOD_NO" IS '상품 번호';
COMMENT ON COLUMN "CART"."COUNT" IS '수량';
COMMENT ON COLUMN "CART"."STATUS" IS '구매여부';

//==============================================================================
// 좋아요 테이블 생성
CREATE TABLE "LIKE" (
	"MEMBER_NO"	    NUMBER		NOT NULL,
	"GOOD_NO"	    NUMBER		NOT NULL
);

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "LIKE"."GOOD_NO" IS '상품 번호';

//==============================================================================
// 찜 테이블 생성
CREATE TABLE "SUBSCRIBE" (
	"MEMBER_NO"	        NUMBER		NOT NULL,
	"SELLER_NO"         NUMBER		NOT NULL
);

COMMENT ON COLUMN "SUBSCRIBE"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "SUBSCRIBE"."SELLER_NO" IS '판매자 번호';

//==============================================================================
// 상품 판매 댓글 테이블 생성
CREATE TABLE "SELL_REPLY" (
	"REPLY_NO"	    NUMBER		        NOT NULL,
	"MEMBER_NO"	    NUMBER		        NOT NULL,
	"SELL_NO"	    NUMBER		        NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(100)		NOT NULL,
	"CREATE_DATE"	DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	DATE		        NULL
);

COMMENT ON COLUMN "SELL_REPLY"."REPLY_NO" IS '댓글 번호';
COMMENT ON COLUMN "SELL_REPLY"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "SELL_REPLY"."SELL_NO" IS '상품 판매 번호';
COMMENT ON COLUMN "SELL_REPLY"."REPLY_CONTENT" IS '내용';
COMMENT ON COLUMN "SELL_REPLY"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "SELL_REPLY"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 홍보 댓글 테이블 생성
CREATE TABLE "PROMOTION_REPLY" (
	"REPLY_NO"	        NUMBER		        NOT NULL,
	"PROMOTION_NO"	    NUMBER		        NOT NULL,
	"MEMBER_NO"	        NUMBER		        NOT NULL,
	"REPLY_CONTENT"	    VARCHAR2(3000)		NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "PROMOTION_REPLY"."REPLY_NO" IS '댓글 번호';
COMMENT ON COLUMN "PROMOTION_REPLY"."PROMOTION_NO" IS '홍보 번호';
COMMENT ON COLUMN "PROMOTION_REPLY"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "PROMOTION_REPLY"."REPLY_CONTENT" IS '내용';
COMMENT ON COLUMN "PROMOTION_REPLY"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "PROMOTION_REPLY"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 후기 댓글 테이블 생성
CREATE TABLE "REVIEW_REPLY" (
	"REPLY_NO"	        NUMBER		        NOT NULL,
    "REV_NO"	        NUMBER		        NOT NULL,
	"MEMBER_NO"	        NUMBER		        NOT NULL,
	"REPLY_CONTENT"	    VARCHAR2(3000)		NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL 
);

COMMENT ON COLUMN "REVIEW_REPLY"."REPLY_NO" IS '댓글 번호';
COMMENT ON COLUMN "REVIEW_REPLY"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "REVIEW_REPLY"."REV_NO" IS '후기 번호';
COMMENT ON COLUMN "REVIEW_REPLY"."REPLY_CONTENT" IS '내용';
COMMENT ON COLUMN "REVIEW_REPLY"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "REVIEW_REPLY"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 문의 댓글 테이블 생성
CREATE TABLE "INQUIRY_REPLY" (
	"REPLY_NO"	        NUMBER		        NOT NULL,
	"INQ_NO"	        NUMBER		        NOT NULL,
	"MEMBER_NO"	        NUMBER		        NOT NULL,
	"REPLY_CONTENT"	    VARCHAR2(3000)		NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "INQUIRY_REPLY"."REPLY_NO" IS '댓글 번호';
COMMENT ON COLUMN "INQUIRY_REPLY"."INQ_NO" IS '문의 번호';
COMMENT ON COLUMN "INQUIRY_REPLY"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "INQUIRY_REPLY"."REPLY_CONTENT" IS '내용';
COMMENT ON COLUMN "INQUIRY_REPLY"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "INQUIRY_REPLY"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 공지 파일 테이블 생성
CREATE TABLE "NOTICE_FILE" (
	"FILE_NO"	        NUMBER		        NOT NULL,
	"NOTICE_NO"	        NUMBER		        NOT NULL,
	"ORIGIN_NAME"	    VARCHAR2(400)		NOT NULL,
	"CHANGE_NAME"	    VARCHAR2(400)		NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "NOTICE_FILE"."FILE_NO" IS '파일 번호';
COMMENT ON COLUMN "NOTICE_FILE"."NOTICE_NO" IS '공지사항 번호';
COMMENT ON COLUMN "NOTICE_FILE"."ORIGIN_NAME" IS '원본명';
COMMENT ON COLUMN "NOTICE_FILE"."CHANGE_NAME" IS '수정명';
COMMENT ON COLUMN "NOTICE_FILE"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "NOTICE_FILE"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 판매자 파일 테이블 생성
CREATE TABLE "SELLER_FILE" (
	"FILE_NO"	    NUMBER		        NOT NULL,
	"SELLER_NO"	    NUMBER		        NOT NULL,
	"ORIGINAL_NAME"	VARCHAR2(400)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(400)		NOT NULL,
	"CREATE_DATE"	DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	DATE		        NULL
);

COMMENT ON COLUMN "SELLER_FILE"."FILE_NO" IS '파일 번호';
COMMENT ON COLUMN "SELLER_FILE"."SELLER_NO" IS '판매자 번호';
COMMENT ON COLUMN "SELLER_FILE"."ORIGINAL_NAME" IS '원본명';
COMMENT ON COLUMN "SELLER_FILE"."CHANGE_NAME" IS '수정명';
COMMENT ON COLUMN "SELLER_FILE"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "SELLER_FILE"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 상품 파일 테이블 생성
CREATE TABLE "GOODS_FILE" (
	"FILE_NO"	        NUMBER		        NOT NULL,
	"SELL_NO"	        NUMBER		        NOT NULL,
	"ORIGINAL_NAME"	    VARCHAR2(300)		NOT NULL,
	"CHANGE_NAME"	    VARCHAR2(300)		NOT NULL,
	"CREATE_DATE"	    DATE	            NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "GOODS_FILE"."FILE_NO" IS '파일 번호';
COMMENT ON COLUMN "GOODS_FILE"."SELL_NO" IS '상품 판매 번호';
COMMENT ON COLUMN "GOODS_FILE"."ORIGINAL_NAME" IS '원본명';
COMMENT ON COLUMN "GOODS_FILE"."CHANGE_NAME" IS '수정명';
COMMENT ON COLUMN "GOODS_FILE"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "GOODS_FILE"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 후기 파일 테이블 생성
CREATE TABLE "REVIEW_FILE" (
	"FILE_NO"	    NUMBER		        NOT NULL,
	"REV_NO"	    NUMBER		        NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(400)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(400)		NOT NULL,
	"CREATE_DATE"	DATE	            NULL,
	"DELETE_DATE"	DATE		        NULL
);

COMMENT ON COLUMN "REVIEW_FILE"."FILE_NO" IS '파일 번호';
COMMENT ON COLUMN "REVIEW_FILE"."REV_NO" IS '후기 번호';
COMMENT ON COLUMN "REVIEW_FILE"."ORIGIN_NAME" IS '원본명';
COMMENT ON COLUMN "REVIEW_FILE"."CHANGE_NAME" IS '수정명';
COMMENT ON COLUMN "REVIEW_FILE"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "REVIEW_FILE"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 홍보 파일 테이블 생성
CREATE TABLE "PROMOTION_FILE" (
	"FILE_NO"	        NUMBER		        NOT NULL,
	"PROMOTION_NO"	    NUMBER		        NOT NULL,
	"ORIGINAL_NAME"	    VARCHAR2(300)		NOT NULL,
	"CHANGE_NAME"	    VARCHAR2(300)		NOT NULL,
	"CREATE_DATE"	    DATE	            NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "PROMOTION_FILE"."FILE_NO" IS '파일 번호';
COMMENT ON COLUMN "PROMOTION_FILE"."PROMOTION_NO" IS '홍보 번호';
COMMENT ON COLUMN "PROMOTION_FILE"."ORIGINAL_NAME" IS '원본명';
COMMENT ON COLUMN "PROMOTION_FILE"."CHANGE_NAME" IS '수정명';
COMMENT ON COLUMN "PROMOTION_FILE"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "PROMOTION_FILE"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 문의 파일 테이블 생성
CREATE TABLE "INQUIRY_FILE" (
	"FILE_NO"	        NUMBER		        NOT NULL,
	"INQ_NO"	        NUMBER		        NOT NULL,
	"ORIGIN_NAME"	    VARCHAR2(400)		NOT NULL,
	"CHANGE_NAME"	    VARCHAR2(400)		NOT NULL,
	"CREATE_DATE"	    DATE	            DEFAULT SYSDATE	NOT NULL,
	"DELETE_DATE"	    DATE		        NULL
);

COMMENT ON COLUMN "INQUIRY_FILE"."FILE_NO" IS '파일 번호';
COMMENT ON COLUMN "INQUIRY_FILE"."INQ_NO" IS '문의 번호';
COMMENT ON COLUMN "INQUIRY_FILE"."ORIGIN_NAME" IS '원본명';
COMMENT ON COLUMN "INQUIRY_FILE"."CHANGE_NAME" IS '수정명';
COMMENT ON COLUMN "INQUIRY_FILE"."CREATE_DATE" IS '등록일';
COMMENT ON COLUMN "INQUIRY_FILE"."DELETE_DATE" IS '삭제일';

//==============================================================================
// 식별자 추가
ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"CART_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REV_NO"
);

ALTER TABLE "INQUIRY_REPLY" ADD CONSTRAINT "PK_INQUIRY_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "GOODS_SELL" ADD CONSTRAINT "PK_GOODS_SELL" PRIMARY KEY (
	"SELL_NO"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY (
	"INQ_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDER_NO"
);

ALTER TABLE "ORDER_GOODS" ADD CONSTRAINT "PK_ORDER_GOODS" PRIMARY KEY (
	"ORDER_DETAIL_NO"
);

ALTER TABLE "GOODS" ADD CONSTRAINT "PK_GOODS" PRIMARY KEY (
	"GOOD_NO"
);

ALTER TABLE "NOTICE_FILE" ADD CONSTRAINT "PK_NOTICE_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "SELLER" ADD CONSTRAINT "PK_SELLER" PRIMARY KEY (
	"SELLER_NO"
);

ALTER TABLE "PROMOTION" ADD CONSTRAINT "PK_PROMOTION" PRIMARY KEY (
	"PROMOTION_NO"
);

ALTER TABLE "SELLER_FILE" ADD CONSTRAINT "PK_SELLER_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "PROMOTION_REPLY" ADD CONSTRAINT "PK_PROMOTION_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "SELL_REPLY" ADD CONSTRAINT "PK_SELL_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "REVIEW_FILE" ADD CONSTRAINT "PK_REVIEW_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "PROMOTION_FILE" ADD CONSTRAINT "PK_PROMOTION_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "INQUIRY_FILE" ADD CONSTRAINT "PK_INQUIRY_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "GOODS_FILE" ADD CONSTRAINT "PK_GOODS_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "REVIEW_REPLY" ADD CONSTRAINT "PK_REVIEW_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_MEMBER_TO_CART_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_GOODS_TO_CART_1" FOREIGN KEY (
	"GOOD_NO"
)
REFERENCES "GOODS" (
	"GOOD_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_GOODS_TO_REVIEW_1" FOREIGN KEY (
	"GOOD_NO"
)
REFERENCES "GOODS" (
	"GOOD_NO"
);

ALTER TABLE "SUBSCRIBE" ADD CONSTRAINT "FK_MEMBER_TO_SUBSCRIBE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "SUBSCRIBE" ADD CONSTRAINT "FK_SELLER_TO_SUBSCRIBE_1" FOREIGN KEY (
	"SELLER_NO"
)
REFERENCES "SELLER" (
	"SELLER_NO"
);

ALTER TABLE "INQUIRY_REPLY" ADD CONSTRAINT "FK_INQUIRY_TO_INQUIRY_REPLY_1" FOREIGN KEY (
	"INQ_NO"
)
REFERENCES "INQUIRY" (
	"INQ_NO"
);

ALTER TABLE "INQUIRY_REPLY" ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_REPLY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "GOODS_SELL" ADD CONSTRAINT "FK_SELLER_TO_GOODS_SELL_1" FOREIGN KEY (
	"SELLER_NO"
)
REFERENCES "SELLER" (
	"SELLER_NO"
);

ALTER TABLE "GOODS_SELL" ADD CONSTRAINT "FK_GOODS_TO_GOODS_SELL_1" FOREIGN KEY (
	"GOOD_NO"
)
REFERENCES "GOODS" (
	"GOOD_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_GOODS_TO_LIKE_1" FOREIGN KEY (
	"GOOD_NO"
)
REFERENCES "GOODS" (
	"GOOD_NO"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "FK_SELLER_TO_INQUIRY_1" FOREIGN KEY (
	"SELLER_NO"
)
REFERENCES "SELLER" (
	"SELLER_NO"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_MEMBER_TO_ORDER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "ORDER_GOODS" ADD CONSTRAINT "FK_ORDER_TO_ORDER_GOODS_1" FOREIGN KEY (
	"ORDER_NO"
)
REFERENCES "ORDER" (
	"ORDER_NO"
);

ALTER TABLE "ORDER_GOODS" ADD CONSTRAINT "FK_GOODS_TO_ORDER_GOODS_1" FOREIGN KEY (
	"GOOD_NO"
)
REFERENCES "GOODS" (
	"GOOD_NO"
);

ALTER TABLE "GOODS" ADD CONSTRAINT "FK_SELLER_TO_GOODS_1" FOREIGN KEY (
	"SELLER_NO"
)
REFERENCES "SELLER" (
	"SELLER_NO"
);

ALTER TABLE "NOTICE_FILE" ADD CONSTRAINT "FK_NOTICE_TO_NOTICE_FILE_1" FOREIGN KEY (
	"NOTICE_NO"
)
REFERENCES "NOTICE" (
	"NOTICE_NO"
);

ALTER TABLE "PROMOTION" ADD CONSTRAINT "FK_SELLER_TO_PROMOTION_1" FOREIGN KEY (
	"SELLER_NO"
)
REFERENCES "SELLER" (
	"SELLER_NO"
);

ALTER TABLE "SELLER_FILE" ADD CONSTRAINT "FK_SELLER_TO_SELLER_FILE_1" FOREIGN KEY (
	"SELLER_NO"
)
REFERENCES "SELLER" (
	"SELLER_NO"
);

ALTER TABLE "PROMOTION_REPLY" ADD CONSTRAINT "FK_PRO_TO_PROMOTION_REPLY_1" FOREIGN KEY (
	"PROMOTION_NO"
)
REFERENCES "PROMOTION" (
	"PROMOTION_NO"
);

ALTER TABLE "PROMOTION_REPLY" ADD CONSTRAINT "FK_MEMBER_TO_PROMOTION_REPLY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "SELL_REPLY" ADD CONSTRAINT "FK_MEMBER_TO_SELL_REPLY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "SELL_REPLY" ADD CONSTRAINT "FK_GOODS_SELL_TO_SELL_REPLY_1" FOREIGN KEY (
	"SELL_NO"
)
REFERENCES "GOODS_SELL" (
	"SELL_NO"
);

ALTER TABLE "REVIEW_FILE" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_FILE_1" FOREIGN KEY (
	"REV_NO"
)
REFERENCES "REVIEW" (
	"REV_NO"
);

ALTER TABLE "PROMOTION_FILE" ADD CONSTRAINT "FK_PRO_TO_PROMOTION_FILE_1" FOREIGN KEY (
	"PROMOTION_NO"
)
REFERENCES "PROMOTION" (
	"PROMOTION_NO"
);

ALTER TABLE "INQUIRY_FILE" ADD CONSTRAINT "FK_INQUIRY_TO_INQUIRY_FILE_1" FOREIGN KEY (
	"INQ_NO"
)
REFERENCES "INQUIRY" (
	"INQ_NO"
);

ALTER TABLE "GOODS_FILE" ADD CONSTRAINT "FK_GOODS_SELL_TO_GOODS_FILE_1" FOREIGN KEY (
	"SELL_NO"
)
REFERENCES "GOODS_SELL" (
	"SELL_NO"
);

ALTER TABLE "REVIEW_REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_REPLY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "REVIEW_REPLY" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_REPLY_1" FOREIGN KEY (
	"REV_NO"
)
REFERENCES "REVIEW" (
	"REV_NO"
);

// ------------------------------ 더미데이터 --------------------------------
REM INSERTING into FTD.MEMBER
SET DEFINE OFF;
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'admin','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','어드민','admin@gmail.com','010-2222-5875','11073','경기도 광명시 광명동','광명동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user01','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','엄규율','user01@gmail.com','010-4125-3774','46833','대구광역시 수성구 범어동','범어동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user02','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','공의예','user02@gmail.com','010-4816-2504','10796','부산광역시 수영구 광안동','광안동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user03','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','나선옥','user03@gmail.com','010-4085-8750','20920','경기도 안산시 단원구 선부동','선부동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user04','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','방지유','user04@gmail.com','010-1047-4846','51352','경기도 광명시 철산동','철산동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user05','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','고해원','user05@gmail.com','010-3422-1376','46498','서울특별시 강동구 암사동','암사동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user06','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','원하욱','user06@gmail.com','010-2504-3285','58493','인천광역시 부평구 부개동','부개동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user07','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','신률승','user07@gmail.com','010-2664-0256','57866','서울특별시 강동구 성내동','성내동 아파트','F',to_date('23/12/23','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user08','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','남은령','user08@gmail.com','010-5242-3804','73818','충청북도 청주시 흥덕구 복대동','복대동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user09','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','탁송린','user09@gmail.com','010-3326-2631','31938','대구광역시 달서구 상인동','상인동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user10','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','윤소휘','user10@gmail.com','010-1233-6157','10616','서울특별시 은평구 불광동','불광동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user11','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','박여세','user11@gmail.com','010-1756-1061','59347','부산광역시 사하구 다대동','다대동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user12','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','황아운','user12@gmail.com','010-8567-7522','93839','대전광역시 서구 관저동','관저동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user13','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','우정림','user13@gmail.com','010-4400-8225','20490','인천광역시 계양구 계산동','계산동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user14','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','서정예','user14@gmail.com','010-2527-8283','90946','경기도 파주시 목동동','목동동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user15','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','변태효','user15@gmail.com','010-6514-3223','96601','경기도 안양시 만안구 석수동','석수동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user16','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','우보예','user16@gmail.com','010-5165-8425','80661','서울특별시 송파구 문정동','문정동 아파트','M',to_date('24/03/08','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user17','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','백원안','user17@gmail.com','010-8182-0587','29295','부산광역시 북구 만덕동','만덕동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user18','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','최수운','user18@gmail.com','010-5045-6816','43889','서울특별시 강남구 개포동','개포동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user19','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','도시한','user19@gmail.com','010-6212-3771','38334','인천광역시 부평구 삼산동','삼산동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user20','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','손고우','user20@gmail.com','010-2536-5556','99059','인천광역시 연수구 동춘동','동춘동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user21','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','추비우','user21@gmail.com','010-3677-3630','43413','부산광역시 해운대구 재송동','재송동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user22','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','장다현','user22@gmail.com','010-6373-7666','58372','경기도 성남시 분당구 야탑동','야탑동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user23','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','차의리','user23@gmail.com','010-8086-3010','55844','경기도 김포시 풍무동','풍무동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user24','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','민나원','user24@gmail.com','010-2684-1128','79523','부산광역시 연제구 거제동','거제동 아파트','M',to_date('24/01/01','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user25','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','민도운','user25@gmail.com','010-3628-0330','44231','경기도 화성시 병점동','병점동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user26','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','유재진','user26@gmail.com','010-8040-8435','42956','부산광역시 북구 구포동','구포동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user27','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','황세나','user27@gmail.com','010-7674-6832','27052','경기도 평택시 비전동','비전동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user28','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','은준한','user28@gmail.com','010-5745-6785','18429','경기도 수원시 영통구 망포동','망포동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user29','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','전고세','user29@gmail.com','010-1880-3655','26527','서울특별시 송파구 방이동','방이동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user30','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','구시영','user30@gmail.com','010-5862-4007','90248','경기도 하남시 덕풍동','덕풍동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user31','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','조우현','user31@gmail.com','010-3354-3624','84047','경기도 광명시 소하동','소하동 아파트','F',to_date('24/02/13','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user32','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','차하민','user32@gmail.com','010-2832-8620','35779','인천광역시 서구 가좌동','가좌동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user33','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','편준향','user33@gmail.com','010-1880-4211','60351','부산광역시 사하구 괴정동','괴정동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user34','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','강초은','user34@gmail.com','010-0186-1174','18171','서울특별시 중랑구 신내동','신내동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user35','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','염초기','user35@gmail.com','010-6622-2423','42592','경기도 파주시 동패동','동패동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user36','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','지영하','user36@gmail.com','010-6374-3368','96180','대구광역시 달서구 용산동','용산동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user37','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','여경늘','user37@gmail.com','010-5504-1020','95646','경기도 구리시 인창동','인창동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user38','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','편예신','user38@gmail.com','010-2431-7431','38015','경기도 의정부시 의정부동','의정부동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user39','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','송순정','user39@gmail.com','010-0842-4866','51241','경기도 남양주시 호평동','호평동 아파트','F',to_date('24/01/16','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user40','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','곽고기','user40@gmail.com','010-6520-4566','97049','서울특별시 동대문구 답십리동','답십리동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user41','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','오보정','user41@gmail.com','010-4004-0336','91851','경기도 성남시 수정구 태평동','태평동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user42','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','원교혜','user42@gmail.com','010-3107-0052','48611','경기도 양주시 옥정동','옥정동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user43','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','여우예','user43@gmail.com','010-0533-8336','82070','인천광역시 미추홀구 도화동','도화동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user44','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','백비민','user44@gmail.com','010-7365-6255','61073','인천광역시 계양구 효성동','효성동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user45','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','여현송','user45@gmail.com','010-6657-3706','58527','경상남도 양산시 물금읍','물금읍 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user46','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','전승림','user46@gmail.com','010-5682-8855','75467','경기도 고양시 일산서구 주엽동','주엽동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user47','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','박송호','user47@gmail.com','010-8007-2260','43421','부산광역시 부산진구 개금동','개금동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user48','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','이보향','user48@gmail.com','010-5355-5600','30919','충청북도 청주시 흥덕구 가경동','가경동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user49','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','민주현','user49@gmail.com','010-5402-4772','57958','경기도 고양시 일산서구 대화동','대화동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user50','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','나초현','user50@gmail.com','010-4671-4178','77443','경기도 부천시 소사본동','소사본동 아파트','M',to_date('24/01/30','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user51','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','차성리','user51@gmail.com','010-6155-1633','46599','울산광역시 남구 야음동','야음동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user52','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','홍도윤','user52@gmail.com','010-8418-1317','47628','인천광역시 연수구 연수동','연수동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user53','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','양조임','user53@gmail.com','010-6763-7211','24269','경기도 시흥시 은행동','은행동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user54','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','강다언','user54@gmail.com','010-1724-4453','14741','서울특별시 은평구 진관동','진관동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user55','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','오정신','user55@gmail.com','010-5684-1387','93944','경기도 군포시 당동','당동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user56','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','손원임','user56@gmail.com','010-0638-5701','38941','경기도 파주시 야당동','야당동 아파트','M',to_date('24/02/16','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user57','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','차경교','user57@gmail.com','010-5846-4304','21412','서울특별시 강서구 마곡동','마곡동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user58','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','서민혜','user58@gmail.com','010-8433-3773','76371','서울특별시 서대문구 홍제동','홍제동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user59','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','최기정','user59@gmail.com','010-8634-4562','35349','경기도 용인시 수지구 성복동','성복동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user60','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','나률교','user60@gmail.com','010-7731-8243','69823','서울특별시 강남구 도곡동','도곡동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user61','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','방동련','user61@gmail.com','010-6184-0781','72640','경기도 안양시 동안구 평촌동','평촌동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user62','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','노송희','user62@gmail.com','010-5355-8432','88114','서울특별시 성북구 길음동','길음동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user63','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','고태우','user63@gmail.com','010-7887-3558','31463','경상남도 양산시 물금읍','물금읍 아파트','F',to_date('24/02/13','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user64','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','탁준욱','user64@gmail.com','010-2276-0845','20220','부산광역시 금정구 부곡동','부곡동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user65','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','민비완','user65@gmail.com','010-0061-7331','64273','광주광역시 서구 화정동','화정동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user66','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','한우진','user66@gmail.com','010-7270-0023','25379','부산광역시 동래구 사직동','사직동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user67','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','장비영','user67@gmail.com','010-3020-2581','45579','서울특별시 성북구 장위동','장위동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user68','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','진재비','user68@gmail.com','010-5026-8215','13193','인천광역시 남동구 서창동','서창동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user69','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','문교영','user69@gmail.com','010-8858-6134','70842','대구광역시 달서구 월성동','월성동 아파트','F',to_date('24/02/24','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user70','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','엄지정','user70@gmail.com','010-4701-6472','22309','서울특별시 중랑구 묵동','묵동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user71','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','나아연','user71@gmail.com','010-8428-6433','58141','경기도 수원시 영통구 이의동','이의동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user72','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','변상효','user72@gmail.com','010-0457-1614','78758','경기도 화성시 청계동','청계동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user73','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','하솔호','user73@gmail.com','010-0211-4351','36482','인천광역시 부평구 십정동','십정동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user74','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','하다성','user74@gmail.com','010-6744-4641','76364','경기도 의정부시 민락동','민락동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user75','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','강조늘','user75@gmail.com','010-1074-8183','89407','제주특별자치도 제주시 노형동','노형동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user76','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','한경소','user76@gmail.com','010-5172-5437','29150','인천광역시 서구 당하동','당하동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user77','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','편예온','user77@gmail.com','010-5514-2664','65772','대구광역시 수성구 만촌동','만촌동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user78','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','서한원','user78@gmail.com','010-7128-0773','42932','경기도 수원시 권선구 세류동','세류동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user79','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','장솔진','user79@gmail.com','010-0450-7547','48412','서울특별시 송파구 거여동','거여동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user80','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','고해수','user80@gmail.com','010-2742-5341','35166','전라북도 군산시 나운동','나운동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user81','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','추상호','user81@gmail.com','010-3578-5874','89897','울산광역시 남구 무거동','무거동 아파트','F',to_date('24/02/26','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user82','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','염하완','user82@gmail.com','010-2267-8036','63672','부산광역시 금정구 구서동','구서동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user83','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','추윤진','user83@gmail.com','010-2311-7288','23904','서울특별시 중랑구 망우동','망우동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user84','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','하양교','user84@gmail.com','010-0214-1483','43777','경기도 군포시 금정동','금정동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user85','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','한세비','user85@gmail.com','010-5043-0860','79713','전라북도 전주시 덕진구 송천동2가','송천동2가 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user86','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','우한언','user86@gmail.com','010-5175-8681','10462','대구광역시 서구 비산동','비산동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user87','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','정한진','user87@gmail.com','010-3781-2321','73608','전라북도 전주시 덕진구 인후동1가','인후동1가 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user88','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','문은희','user88@gmail.com','010-5783-7226','50669','경기도 의정부시 가능동','가능동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user89','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','나상비','user89@gmail.com','010-3218-5063','46705','경기도 파주시 금촌동','금촌동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user90','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','최지련','user90@gmail.com','010-6046-3302','41998','인천광역시 서구 마전동','마전동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user91','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','윤태비','user91@gmail.com','010-3813-5611','43671','경기도 고양시 일산동구 백석동','백석동 아파트','F',to_date('24/03/05','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user92','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','곽연유','user92@gmail.com','010-6362-8323','58728','경상남도 김해시 삼계동','삼계동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user93','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','양률주','user93@gmail.com','010-7115-4052','68695','서울특별시 강동구 상일동','상일동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user94','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','표희운','user94@gmail.com','010-1441-8562','50446','인천광역시 서구 가정동','가정동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user95','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','최준미','user95@gmail.com','010-6687-1805','45620','경기도 고양시 일산서구 탄현동','탄현동 아파트','F',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user96','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','공경예','user96@gmail.com','010-1811-3342','51465','부산광역시 사상구 주례동','주례동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user97','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','전해아','user97@gmail.com','010-6172-2362','68815','전라남도 순천시 조례동','조례동 아파트','F',to_date('24/03/07','RR/MM/DD'));
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user98','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','도지언','user98@gmail.com','010-2710-2821','63211','경기도 부천시 원종동','원종동 아파트','M',null);
Insert into FTD.MEMBER (MEMBER_NO,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,EMAIL,PHONE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,GENDER,STATUS) values (SEQ_MNO.NEXTVAL,'user99','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','허한령','user99@gmail.com','010-5442-3317','33305','서울특별시 강북구 번동','번동 아파트','F',null);
REM INSERTING into FTD.SELLER
SET DEFINE OFF;
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'박재림네 야채가게','seller01','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','박재림','123-12-12345','1911-서울특별시-1112','서울특별시 관악구 봉천동','seller01@gmail.com','010-2611-7643','111-2222-3333-44',null,to_date('23/11/30','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'주다채네 야채가게','seller02','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','주다채','123-12-12346','1912-서울특별시-1113','서울특별시 강서구 화곡동','seller02@gmail.com','010-6658-7433','111-2222-3333-44',to_date('23/12/19','RR/MM/DD'),to_date('23/12/01','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'권비비네 야채가게','seller03','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','권비비','123-12-12347','1913-서울특별시-1114','서울특별시 노원구 상계동','seller03@gmail.com','010-7433-2348','111-2222-3333-44',null,to_date('23/12/02','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'방기유네 야채가게','seller04','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','방기유','123-12-12348','1914-인천광역시-1115','인천광역시 연수구 송도동','seller04@gmail.com','010-2242-1552','111-2222-3333-44',null,to_date('23/12/03','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'추선호네 야채가게','seller05','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','추선호','123-12-12349','1915-서울특별시-1116','서울특별시 양천구 신정동','seller05@gmail.com','010-2487-3281','111-2222-3333-44',null,to_date('23/12/04','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'남여란네 야채가게','seller06','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','남여란','123-12-12350','1916-서울특별시-1117','서울특별시 양천구 목동','seller06@gmail.com','010-5701-8074','111-2222-3333-44',null,to_date('23/12/05','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'김승솔네 야채가게','seller07','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','김승솔','123-12-12351','1917-부산광역시-1118','부산광역시 연제구 연산동','seller07@gmail.com','010-5556-4027','111-2222-3333-44',null,to_date('23/12/06','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'지조리네 야채가게','seller08','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','지조리','123-12-12352','1918-인천광역시-1119','인천광역시 부평구 부평동','seller08@gmail.com','010-2275-2121','111-2222-3333-44',null,to_date('23/12/07','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'홍슬연네 야채가게','seller09','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','홍슬연','123-12-12353','1919-서울특별시-1120','서울특별시 중랑구 면목동','seller09@gmail.com','010-1253-4484','111-2222-3333-44',null,to_date('23/12/08','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'민성정네 야채가게','seller10','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','민성정','123-12-12354','1920-경기도-1121','경기도 안양시 만안구 안양동','seller10@gmail.com','010-5164-3202','111-2222-3333-44',null,to_date('23/12/09','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'신은우네 야채가게','seller11','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','신은우','123-12-12355','1921-인천광역시-1122','인천광역시 미추홀구 주안동','seller11@gmail.com','010-3854-8872','111-2222-3333-44',null,to_date('23/12/10','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'곽해효네 야채가게','seller12','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','곽해효','123-12-12356','1922-경기도-1123','경기도 부천시 중동','seller12@gmail.com','010-1151-3283','111-2222-3333-44',null,to_date('23/12/11','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'곽한선네 야채가게','seller13','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','곽한선','123-12-12357','1923-서울특별시-1124','서울특별시 강북구 미아동','seller13@gmail.com','010-5785-3401','111-2222-3333-44',null,to_date('23/12/12','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'문준한네 야채가게','seller14','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','문준한','123-12-12358','1924-경기도-1125','경기도 남양주시 다산동','seller14@gmail.com','010-5102-2738','111-2222-3333-44',null,to_date('23/12/13','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'진영정네 야채가게','seller15','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','진영정','123-12-12359','1925-서울특별시-1126','서울특별시 양천구 신월동','seller15@gmail.com','010-2512-5612','111-2222-3333-44',null,to_date('23/12/14','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'방슬정네 야채가게','seller16','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','방슬정','123-12-12360','1926-인천광역시-1127','인천광역시 남동구 만수동','seller16@gmail.com','010-4312-7702','111-2222-3333-44',null,to_date('23/12/15','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'나보윤네 야채가게','seller17','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','나보윤','123-12-12361','1927-서울특별시-1128','서울특별시 도봉구 창동','seller17@gmail.com','010-1374-2378','111-2222-3333-44',to_date('23/12/19','RR/MM/DD'),to_date('23/12/16','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'곽소현네 야채가게','seller18','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','곽소현','123-12-12362','1928-서울특별시-1129','서울특별시 구로구 구로동','seller18@gmail.com','010-7477-7583','111-2222-3333-44',null,to_date('23/12/17','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'송보윤네 야채가게','seller19','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','송보윤','123-12-12363','1929-서울특별시-1130','서울특별시 동작구 상도동','seller19@gmail.com','010-6687-1677','111-2222-3333-44',null,to_date('23/12/18','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'지률예네 야채가게','seller20','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','지률예','123-12-12364','1930-경기도-1131','경기도 시흥시 정왕동','seller20@gmail.com','010-6618-3727','111-2222-3333-44',null,to_date('23/12/19','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'황혜경네 야채가게','seller21','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','황혜경','123-12-12365','1931-인천광역시-1132','인천광역시 서구 청라동','seller21@gmail.com','010-1708-8858','111-2222-3333-44',null,to_date('23/12/20','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'고연하네 야채가게','seller22','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','고연하','123-12-12366','1932-인천광역시-1133','인천광역시 남동구 구월동','seller22@gmail.com','010-6230-8347','111-2222-3333-44',null,to_date('23/12/21','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'신성서네 야채가게','seller23','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','신성서','123-12-12367','1933-경기도-1134','경기도 군포시 산본동','seller23@gmail.com','010-3641-8104','111-2222-3333-44',null,to_date('23/12/22','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'방희교네 야채가게','seller24','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','방희교','123-12-12368','1934-서울특별시-1135','서울특별시 서초구 서초동','seller24@gmail.com','010-4075-1840','111-2222-3333-44',null,to_date('23/12/23','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'하아유네 야채가게','seller25','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','하아유','123-12-12369','1935-서울특별시-1136','서울특별시 송파구 잠실동','seller25@gmail.com','010-2058-4847','111-2222-3333-44',null,to_date('23/12/24','RR/MM/DD'),null,null);
Insert into FTD.SELLER (SELLER_NO,COMPANY_NAME,SELLER_ID,SELLER_PWD,SELLER_NAME,COMPANY_NO,BUSINESS_NO,ADDRESS,EMAIL,PHONE,ACCOUNT_NO,DELETE_DATE,ENROLL_DATE,ACCEPT_DATE,REFUSE_REASON) values (SEQ_SNO.NEXTVAL,'김혜솔네 야채가게','seller26','$2a$10$TzwJY6QWPUor0dgui.eDo.jrTxrTeF/SokITU2rzIE8NPjFL2F3V2','김혜솔','123-12-12370','1936-경기도-1137','경기도 안산시 상록구 사동','seller26@gmail.com','010-1008-2673','111-2222-3333-44',null,to_date('23/12/25','RR/MM/DD'),null,null);
REM INSERTING into FTD.GOODS
SET DEFINE OFF;
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,12,'파','깐 대파 3kg','부산광역시',25500,to_date('23/12/19','RR/MM/DD'),null,to_date('24/05/06','RR/MM/DD'),28);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,12,'감자','햇 수미감자 5kg 대','경북 청송군',14900,to_date('23/12/19','RR/MM/DD'),null,to_date('24/09/07','RR/MM/DD'),55);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,1,'바나나','바나나','베트남',5380,to_date('23/12/19','RR/MM/DD'),null,to_date('23/12/26','RR/MM/DD'),0);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,1,'블루베리','과일','대한민국',14300,to_date('23/12/19','RR/MM/DD'),null,to_date('23/12/27','RR/MM/DD'),10);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,3,'블루베리','과일','대한민국',14300,to_date('23/12/19','RR/MM/DD'),to_date('23/12/19','RR/MM/DD'),to_date('23/12/28','RR/MM/DD'),10);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,3,'블루베리','과일','대한민국',14300,to_date('23/12/19','RR/MM/DD'),null,to_date('23/12/29','RR/MM/DD'),12);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,4,'야채','당근','대한민국',8900,to_date('23/12/19','RR/MM/DD'),null,to_date('24/01/02','RR/MM/DD'),14);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,5,'야채','가지','방글라데시',9900,to_date('23/12/19','RR/MM/DD'),null,to_date('23/12/29','RR/MM/DD'),18);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,6,'야채','토마토','대한민국',14600,to_date('23/12/19','RR/MM/DD'),null,to_date('24/01/04','RR/MM/DD'),55);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,7,'야채','파프리카','수리남',4899,to_date('23/12/19','RR/MM/DD'),null,to_date('23/12/24','RR/MM/DD'),5);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,26,'오이','오이 10개입','경북 청송군',9450,to_date('23/12/19','RR/MM/DD'),null,to_date('24/02/12','RR/MM/DD'),39);
Insert into FTD.GOODS (GOOD_NO,SELLER_NO,GOOD_TITLE,GOOD_DETAIL,ORIGIN,PRICE,CREATE_DATE,DELETE_DATE,EXPIRATION_DATE,STOCK) values (SEQ_GNO.NEXTVAL,26,'당근','세척 햇당근 5kg','제주 구좌',24500,to_date('23/12/19','RR/MM/DD'),null,to_date('24/04/04','RR/MM/DD'),27);
REM INSERTING into FTD.GOODS_SELL
SET DEFINE OFF;
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,12,1,'깐 대파 3kg 한봉지','<p>깐대파입니다.<img src="https://gdimg.gmarket.co.kr/2871817743/still/280?ver=1680157933" style="width: 280px;"></p>',15,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,12,2,'포슬포슬 햇 수미감자 5kg 대','<p><img src="https://gdimg.gmarket.co.kr/1853868118/still/280?ver=1664935518" style="width: 280px;">&nbsp;</p><p><font color="#000000" style="background-color: rgb(255, 255, 0);"><b><span style="font-size: 30px;">햇감자 (대) 찜용입니다!!!</span></b></font><br></p>',7,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,1,3,'바나나','<p>빠나나</p>',19,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,3,5,'블루베리','<p>쁠루뻬리</p>',4,to_date('23/12/19','RR/MM/DD'),to_date('23/12/19','RR/MM/DD'));
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,3,6,'블루베리','<p>블루베리</p>',7,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,4,7,'당근','<p>땅끈</p>',7,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,5,8,'가지','<p>까찌</p>',7,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,6,9,'토마토','<p>토메이토우</p>',5,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,7,10,'파프리카','<p>퐢후리카</p>',2,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,26,11,'오이 10개입','<p>오이</p>',0,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_SELL (SELL_NO,SELLER_NO,GOOD_NO,SELL_TITLE,SELL_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_GSNO.NEXTVAL,26,12,'제주 구좌 세척 햇당근 5kg','<p>제주산 당근</p>',0,to_date('23/12/19','RR/MM/DD'),null);
REM INSERTING into FTD.GOODS_FILE
SET DEFINE OFF;
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,1,'파.jpg','resources/uploadFiles/goods/20231219134952143209.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,2,'감자.webp','resources/uploadFiles/goods/20231219135729118727.webp',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,3,'bananas-1119790_1280.jpg','resources/uploadFiles/goods/20231219140315115470.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,4,'blueberries-2270379_1280.jpg','resources/uploadFiles/goods/20231219140908145440.jpg',to_date('23/12/19','RR/MM/DD'),to_date('23/12/19','RR/MM/DD'));
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,5,'blueberries-2270379_1280.jpg','resources/uploadFiles/goods/20231219141031170341.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,6,'carrots-2387394_1280.jpg','resources/uploadFiles/goods/20231219141139125037.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,7,'eggplant.jpg','resources/uploadFiles/goods/20231219141928123651.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,8,'tomato.jpg','resources/uploadFiles/goods/20231219142234130957.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,9,'paprika.jpg','resources/uploadFiles/goods/20231219142605135891.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,10,'오이.jpg','resources/uploadFiles/goods/20231219170210124294.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.GOODS_FILE (FILE_NO,SELL_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_GFNO.NEXTVAL,11,'당근.jpg','resources/uploadFiles/goods/20231219170229164780.jpg',to_date('23/12/19','RR/MM/DD'),null);
REM INSERTING into FTD.CART
SET DEFINE OFF;
Insert into FTD.CART (CART_NO,MEMBER_NO,GOOD_NO,COUNT,STATUS) values (SEQ_CNO.NEXTVAL,2,3,7,'Y');
Insert into FTD.CART (CART_NO,MEMBER_NO,GOOD_NO,COUNT,STATUS) values (SEQ_CNO.NEXTVAL,2,3,1,'N');
Insert into FTD.CART (CART_NO,MEMBER_NO,GOOD_NO,COUNT,STATUS) values (SEQ_CNO.NEXTVAL,2,1,5,'Y');
Insert into FTD.CART (CART_NO,MEMBER_NO,GOOD_NO,COUNT,STATUS) values (SEQ_CNO.NEXTVAL,2,3,1,'N');
Insert into FTD.CART (CART_NO,MEMBER_NO,GOOD_NO,COUNT,STATUS) values (SEQ_CNO.NEXTVAL,2,10,6,'Y');
REM INSERTING into FTD.INQUIRY
SET DEFINE OFF;
Insert into FTD.INQUIRY (INQ_NO,SELLER_NO,MEMBER_NO,INQ_TITLE,INQ_CONTENT,COUNT,CREATE_DATE,DELETE_DATE,RESPONSE_CONTENT,RESPONSE_DATE) values (SEQ_INO.NEXTVAL,1,2,'반난나','파나요',4,to_date('23/12/19','RR/MM/DD'),null,null,null);
REM INSERTING into FTD.INQUIRY_FILE
SET DEFINE OFF;
Insert into FTD.INQUIRY_FILE (FILE_NO,INQ_NO,ORIGIN_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_IFNO.NEXTVAL,1,'바나나.jpg','resources/uploadFiles/inquiry/2023121915592777778.jpg',to_date('23/12/19','RR/MM/DD'),null);
REM INSERTING into FTD.INQUIRY_REPLY
SET DEFINE OFF;
REM INSERTING into FTD."LIKE"
SET DEFINE OFF;
Insert into FTD."LIKE" (MEMBER_NO,GOOD_NO) values (2,3);
Insert into FTD."LIKE" (MEMBER_NO,GOOD_NO) values (2,7);
Insert into FTD."LIKE" (MEMBER_NO,GOOD_NO) values (2,2);
Insert into FTD."LIKE" (MEMBER_NO,GOOD_NO) values (2,1);
Insert into FTD."LIKE" (MEMBER_NO,GOOD_NO) values (2,10);
REM INSERTING into FTD.NOTICE
SET DEFINE OFF;
REM INSERTING into FTD.NOTICE_FILE
SET DEFINE OFF;
REM INSERTING into FTD."ORDER"
SET DEFINE OFF;
Insert into FTD."ORDER" (ORDER_NO,MEMBER_NO,ORDER_NAME,PHONE,PRICE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,REQUEST,PAY_TID,PAY_METHOD,PAY_DATE,PAY_CANCEL,STATUS) values (SEQ_ONO.NEXTVAL,2,'엄규율','010-4125-3774',40160,'46833','대구광역시 수성구 범어동','범어동 아파트',null,'T58126f03c8776d36e02','point',to_date('23/12/19','RR/MM/DD'),null,null);
Insert into FTD."ORDER" (ORDER_NO,MEMBER_NO,ORDER_NAME,PHONE,PRICE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,REQUEST,PAY_TID,PAY_METHOD,PAY_DATE,PAY_CANCEL,STATUS) values (SEQ_ONO.NEXTVAL,2,'엄규율','010-4125-3774',130000,'46833','대구광역시 수성구 범어동','범어동 아파트',null,'T58146933ad74821239e','point',to_date('23/12/19','RR/MM/DD'),null,null);
Insert into FTD."ORDER" (ORDER_NO,MEMBER_NO,ORDER_NAME,PHONE,PRICE,ZIP_CODE,ADDRESS,DETAIL_ADDRESS,REQUEST,PAY_TID,PAY_METHOD,PAY_DATE,PAY_CANCEL,STATUS) values (SEQ_ONO.NEXTVAL,2,'엄규율','010-4125-3774',31894,'46833','대구광역시 수성구 범어동','범어동 아파트',null,'T58147043ad7482123ac','point',to_date('23/12/19','RR/MM/DD'),null,null);
REM INSERTING into FTD.ORDER_GOODS
SET DEFINE OFF;
Insert into FTD.ORDER_GOODS (ORDER_DETAIL_NO,ORDER_NO,GOOD_NO,COUNT,PRICE,STATUS) values (SEQ_OGNO.NEXTVAL,1,3,7,5380,'E');
Insert into FTD.ORDER_GOODS (ORDER_DETAIL_NO,ORDER_NO,GOOD_NO,COUNT,PRICE,STATUS) values (SEQ_OGNO.NEXTVAL,2,1,5,25500,'N');
Insert into FTD.ORDER_GOODS (ORDER_DETAIL_NO,ORDER_NO,GOOD_NO,COUNT,PRICE,STATUS) values (SEQ_OGNO.NEXTVAL,3,10,6,4899,'N');
REM INSERTING into FTD.PROMOTION
SET DEFINE OFF;
Insert into FTD.PROMOTION (PROMOTION_NO,SELLER_NO,PROMOTION_TITLE,PROMOTION_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_PNO.NEXTVAL,1,null,'<p>fafdads</p>',16,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.PROMOTION (PROMOTION_NO,SELLER_NO,PROMOTION_TITLE,PROMOTION_CONTENT,COUNT,CREATE_DATE,DELETE_DATE) values (SEQ_PNO.NEXTVAL,26,null,'<p><img src="resources/uploadFiles/promotion/2023121917025259593.jpg" style="width: 530px;"><img src="resources/uploadFiles/promotion/2023121917025881482.jpg" style="width: 50%;"></p><p>오이 당근 팝니다</p>',12,to_date('23/12/19','RR/MM/DD'),null);
REM INSERTING into FTD.PROMOTION_FILE
SET DEFINE OFF;
REM INSERTING into FTD.PROMOTION_REPLY
SET DEFINE OFF;
REM INSERTING into FTD.REVIEW
SET DEFINE OFF;
Insert into FTD.REVIEW (REV_NO,MEMBER_NO,GOOD_NO,REV_TITLE,REV_CONTENT,COUNT,STAR_RATING,CREATE_DATE,DELETE_DATE) values (SEQ_RNO.NEXTVAL,2,3,null,'<p>좋아용</p><p><img src="https://health.chosun.com/site/data/img_dir/2023/07/14/2023071401917_0.jpg" style="width: 640px;"><br></p><p>바나나 좋아용</p><p>수정도 되나요</p>',16,4,to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.REVIEW (REV_NO,MEMBER_NO,GOOD_NO,REV_TITLE,REV_CONTENT,COUNT,STAR_RATING,CREATE_DATE,DELETE_DATE) values (SEQ_RNO.NEXTVAL,2,3,null,'<p>ㄻㄴㄹㄴㅁㄹㄴㄹ</p>',11,5,to_date('23/12/19','RR/MM/DD'),null);
REM INSERTING into FTD.REVIEW_FILE
SET DEFINE OFF;
REM INSERTING into FTD.REVIEW_REPLY
SET DEFINE OFF;
Insert into FTD.REVIEW_REPLY (REPLY_NO,REV_NO,MEMBER_NO,REPLY_CONTENT,CREATE_DATE,DELETE_DATE) values (SEQ_RRNO.NEXTVAL,1,2,'좋아용',to_date('23/12/19','RR/MM/DD'),null);
REM INSERTING into FTD.SELLER_FILE
SET DEFINE OFF;
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,10,'과일가게.png','resources/uploadFiles/sellerPage/d3b0ec3c-0d4f-423b-9160-8495739b4013_과일가게.png',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,11,'채소가게.jpg','resources/uploadFiles/sellerPage/4559fe7f-bbb7-4686-82fc-074cbded8d80_채소가게.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,12,'야채가게.jpg','resources/uploadFiles/sellerPage/a12a5cdf-bf67-4c0d-85c5-20625902c5b2_야채가게.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,1,'apples-805124_1280.jpg','resources/uploadFiles/sellerPage/07e7bb3e-0128-4cbd-ab71-5ed63690b4af_apples-805124_1280.jpg',to_date('23/12/19','RR/MM/DD'),to_date('23/12/19','RR/MM/DD'));
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,1,'bananas-1119790_1280.jpg','resources/uploadFiles/sellerPage/bd7ea813-19ba-4294-9dc5-be768465ae04_bananas-1119790_1280.jpg',to_date('23/12/19','RR/MM/DD'),to_date('23/12/19','RR/MM/DD'));
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,1,'bananas-1119790_1280.jpg','resources/uploadFiles/sellerPage/8b65c1dd-4c17-4bc4-a1bd-b58d25b51857_bananas-1119790_1280.jpg',to_date('23/12/19','RR/MM/DD'),to_date('23/12/19','RR/MM/DD'));
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,20,'1.jpg','resources/uploadFiles/sellerPage/e9a24080-75b8-4407-9bdc-c2f03cc903f2_1.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,21,'2.jpg','resources/uploadFiles/sellerPage/e61cce7b-c6cd-40d3-a93e-55be11e23a68_2.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,22,'3.jpg','resources/uploadFiles/sellerPage/49a78834-6677-4749-a3a7-28196c2c91fa_3.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,23,'4.jpg','resources/uploadFiles/sellerPage/b0bebd19-a3e1-4ca7-84d6-a077875e347c_4.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,1,'bananas-1119790_1280.jpg','resources/uploadFiles/sellerPage/60eff640-bad5-4715-9b13-40946aa883f5_bananas-1119790_1280.jpg',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,24,'5.jpg','resources/uploadFiles/sellerPage/608d374d-7e6b-4b8e-81a1-bf2b5c7ae926_5.jpg',to_date('23/12/19','RR/MM/DD'),to_date('23/12/19','RR/MM/DD'));
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,24,'6.png','resources/uploadFiles/sellerPage/68eb32ec-3f83-43df-90db-0ead02b961b4_6.png',to_date('23/12/19','RR/MM/DD'),null);
Insert into FTD.SELLER_FILE (FILE_NO,SELLER_NO,ORIGINAL_NAME,CHANGE_NAME,CREATE_DATE,DELETE_DATE) values (SEQ_SFNO.NEXTVAL,26,'당곡야채가게.jpg','resources/uploadFiles/sellerPage/2a7a6f17-8539-4b5e-8cca-82b9bb759f88_당곡야채가게.jpg',to_date('23/12/19','RR/MM/DD'),null);
REM INSERTING into FTD.SELL_REPLY
SET DEFINE OFF;
REM INSERTING into FTD.SUBSCRIBE
SET DEFINE OFF;
Insert into FTD.SUBSCRIBE (MEMBER_NO,SELLER_NO) values (2,10);
Insert into FTD.SUBSCRIBE (MEMBER_NO,SELLER_NO) values (2,11);
Insert into FTD.SUBSCRIBE (MEMBER_NO,SELLER_NO) values (3,11);
Insert into FTD.SUBSCRIBE (MEMBER_NO,SELLER_NO) values (2,22);
Insert into FTD.SUBSCRIBE (MEMBER_NO,SELLER_NO) values (2,1);
Insert into FTD.SUBSCRIBE (MEMBER_NO,SELLER_NO) values (3,1);